name:                COPPE
version:             0.1.0.0
github:              "githubuser/COPPE"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/COPPE#readme>

dependencies:
- base >= 4.7 && < 5
- transformers >= 0.5.6.2 && < 0.5.7
- mtl >= 2.2.2 && < 2.3
- tensorflow

library:
  source-dirs: src

executables:
  COPPE-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - COPPE

tests:
  COPPE-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - COPPE
