name:                pygen
version:             0.1.0.0
github:              "githubuser/pygen"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pygen#readme>

dependencies:
- base >= 4.7 && < 5
- language-python >= 0.5.8 && < 0.6
- mtl >= 2.2.2 &&  <= 2.3
- aeson >= 1.5.5.1 && <= 1.5.6

library:
  source-dirs: src

executables:
  pygen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pygen

tests:
  pygen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pygen
